### ISSUE TITLE
ValueError: Renaming of annotated datasets is unsupported

### ISSUE THREAD

**Issue by Purmpol** [monocongo/cvdata#150]
Thanks for your great tool.
However, I got an error when renaming pascal dataset. 

---------------------------------------------------------
$cvdata_rename --annotations_dir anns --images_dir imgs --prefix train --start 0 --digits 3 --format pascal
Traceback (most recent call last):
  File "/home/em/miniconda3/envs/tf2cpu/bin/cvdata_rename", line 8, in <module>
    sys.exit(main())
  File "/home/em/miniconda3/envs/tf2cpu/lib/python3.7/site-packages/cvdata/rename.py", line 102, in main
    raise ValueError("Renaming of annotated datasets is unsupported")
ValueError: Renaming of annotated datasets is unsupported

**Comment by monocongo** [comment]
I apologize for the confusion, @Purmpol , this feature is not supported yet, and that argument (`annotations_dir`) is essentially a place holder.

We allude to this in the README: 
```
In a future release we'll support renaming of image and corresponding annotation files.
```

**Comment by Purmpol** [comment]
Sorry. It's my bad. 
However I hope to see that feature soon.
Your tool helps me a lot. Thank again.

**Comment by monocongo** [comment]
@Purmpol I appreciate your comments, please submit issue for feature request. I don't work on this code very often but that should not be too hard to add.
